### ISSUE TITLE
Footer 1.1 - Create the conditions component

### ISSUE THREAD

**Issue by vante-x** [joannashad/CEN4910#14]
Create a "conditions" component to be later updated it with TOS for the site. 
[Angular Component Documentation - https://angular.io/guide/component-overview](https://angular.io/guide/component-overview)

- [x] Create a new component for conditions titled "conditions" in the app folder.

**Comment by Alayan2** [comment]
1. Created a "conditions" component in the app folder
2. Added draft terms and conditions with minimal styling
3. Added routing link to "Terms and Conditions" link on footer

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/90277439/171683738-3f48779f-9799-40c0-9b26-98c656044898.png">
